name: domi Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Build
        run: go build
      - name: Vet
        run: go vet
      - name: Lint
        run: golint
      - name: Routes Tests
        run: |
          cd routes
          go test -v -coverprofile=coverage.out
          go tool cover -func=coverage.out
